In [ ]:
#Numpy --> Numerical Python

In [ ]:
#import numpy
import numpy as np

In [ ]:
#Creating arrays or matrix
a = np.array([1,2,3]) #1d array
a

b = np.array([[1,2,3],[4,5,6]]) #2d
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#check the dimension
a.shape

(3,)

In [ ]:
b.shape

(2, 3)

In [ ]:
#Array initialization

#create 2*3 matrix of zeros
np.zeros((2,3))

#create 2*3 matrix of ones
np.ones((2,3))

#identity matrix
np.eye(4)

#full of some value
np.full((2,2), 5)

#a range
np.arange(0,10,3)

#linspace
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
#Array properties
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

(3, 3)
9
int64
2


Level 2

In [ ]:
#indexing
a = np.array([10,20,30,40,50])

print(a[1])
print(a[1:4])

20
[20 30 40]


In [ ]:
#2D indexing
b = np.array([[1,2,3],[4,5,6]])
print(b[1,2])
print(b[1])
print(b[:,1])

6
[4 5 6]
[2 5]


In [ ]:
#Flatten
a = np.array([[1,2],[3,4],[5,6]])
print(a.flatten())

#reshape
print(a.reshape(2,3))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


Level -3

In [ ]:
#Arithmetic addition
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

a = np.array([[1,2,3],[4,5,6]])
b = np.array([[2,3,1],[4,2,1]])

print(a+b)
print(a-b)
print(a*b)

[[3 5 4]
 [8 7 7]]
[[-1 -1  2]
 [ 0  3  5]]
[[ 2  6  3]
 [16 10  6]]


In [ ]:
#Statistical operations
a = np.array([[1,2],[3,4]])

print(np.mean(a))
print(np.std(a))
print(np.max(a),np.min(a))
print(np.sum(a, axis=0)) #column wise addition
print(np.sum(a, axis=1)) #row wise addition

2.5
1.118033988749895
4 1
[4 6]
[3 7]


In [ ]:
#Filtering
#Boolean indexing
a = np.array([10,20,30,40,50])
print(a[a>25])

#fancy indexing
idx = [0,2,4]
print(a[idx])

[30 40 50]
[10 30 50]


In [ ]:
#Random
# np.random.randint(1000000,10000000,1)
np.random.randn(2,3)

array([[-0.75912639, -0.66239387,  0.51496033],
       [ 0.53489916,  0.06851881, -2.13911937]])

In [ ]:
#Functions

a = np.array([10,20,30,40,30])

np.where(a==30)
np.unique(a)

#any and all
np.any(a > 25) #any one values matches the condition, then it results true
np.all(a > 25) #all the values ashould match the condition, then it results true

np.False_

In [ ]:
stu = np.array([80,90,50,60,35,78,100])
np.all(stu > 40)

np.False_

In [ ]:
#Sorting
a = np.array([10,5,8])
np.sort(a)

array([ 5,  8, 10])

Level - 4

In [ ]:
#Algebra operations
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

#Matrix Multiplication
print(np.dot(a,b))
print(np.linalg.matrix_transpose(a))
print(np.linalg.det(a))
print(np.linalg.eig(a))

[[19 22]
 [43 50]]
[[1 3]
 [2 4]]
-2.0000000000000004
EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


In [ ]:
#Normalise
data = np.array([100,200,300])

normalised = (data-np.mean(data)) / np.std(data)
normalised

array([-1.22474487,  0.        ,  1.22474487])